### PR TITLE
Move from `master` branch to stable version for `awscr-s3`

### PR DESCRIPTION
**Pull request by stephendolan**
If you use `sitemapper` with [`shrine.cr`](https://github.com/jetrockets/shrine.cr), you'll get an error in your installation:

```
Unable to satisfy the following requirements:

- `awscr-s3 (0.8.0)` required by `shard.lock`
- `awscr-s3 (branch master)` required by `sitemapper 0.7.0`
Failed to resolve dependencies
```

I'm not sure what the original reason was for using master, but the tests pass with the v0.8.0 version and will make this library a bit more stable and less subject to possibly breaking upstream changes in that shard.

### CODE REVIEW

**Review by jwoertink — APPROVED** [review]
Yeah, I prefer the version more. At the time, I think I needed to release a version but didn't want to wait on the aws to release. This is fine now

**Comment by jwoertink** [comment]
Any idea why the checks aren't running?

**Comment by stephendolan** [comment]
@jwoertink I think it's because I made both PRs before either one was merged, so the old checks still ran for this one.

Weird that merging in a change to workflows in master doesn't retrigger the checks on open PRs as well, though :/

**Comment by stephendolan** [comment]
Oh, and this one *might* be worth cutting a release for since I suppose it's possible folks were leveraging functionality that's only in the master branch or something.

**Comment by jwoertink** [comment]
Can you rebase? I'm thinking maybe since I merged in the other one, that change needs to be merged in here.

**Comment by stephendolan** [comment]
@jwoertink, okay, rebased and also added back in the nightly builds! I'm going to submit a PR to the AWS repo to fix that deprecation warning that became an error. This should be good to merge, though, since it passed for `latest`.

Very cool to see this adding value immediately!

**Comment by stephendolan** [comment]
Created https://github.com/taylorfinnell/awscr-s3/issues/85

**Comment by stephendolan** [comment]
@jwoertink I've finally figured out how to flag a version as experimental in these actions! I'd suggest that you make only the `latest` Crystal checks "Required" (or omit required checks completely), but this one should show as passing even though the nightly build fails because of an Ameba issue.

**Comment by jwoertink** [comment]
Ok, I saw there was `specs (latest, false)` and `specs (crystallang/crystal:latest-alpine)`. What's the difference, and should I keep both?

**Comment by stephendolan** [comment]
I want to make sure I'm not bumping code and then leaving you high and dry to figure it out, so I'll give you a quick walkthrough of the new action stuff!

Here's how the matrix is defined:

```yml
      matrix:
        crystal_version:
          - latest
        experimental:
          - false
        include:
          - crystal_version: nightly
            experimental: true
```

The top two keys are "defaults". If you wanted to test Sitemapper with Crystal 0.34.0, all you'd need to do is add `- 0.34.0` under `- latest`, and the tests will start running against `0.34.0` as a non-experimental version (failures actually cause the checks to fail), since `experimental: [false]` is the default.

The `include` item is mainly just to specify experimental builds.

Ultimately, though, *this* is where the output names are coming from. Think of those parenthetical values as `(crystal_version, experimental)`, where we end up with the following:

- `check_format (latest, false)`
- `check_format (nightly, true)`
- `specs (latest, false)`
- `specs (nightly, true)`

If we added Crystal 0.34.0 as a non-experimental version, you'd get two additional runs:

- `check_format (0.34.0, false)`
- `specs (0.34.0, false)`

Does that make more sense?

**Comment by jwoertink** [comment]
Ah, ok. So then the ones that just say `latest-alpine` aren't really needed now?

**Comment by stephendolan** [comment]
@jwoertink Exactly right!

**Review by jwoertink — APPROVED** [review]
Sweet. Thanks for this! We can worry about the failing ones after this.

**Pull request merged**
